### ISSUE TITLE
jobs moeten parallel uitgevoerd worden

### ISSUE THREAD

**Issue by samalloing** [Kris-LIBIS/LIBIS_Ingester#1]
De jobs in de queue moeten parallel uitgevoerd kunnen worden. Het gaat dan hier voornamelijk over het uitvoeren van verschillende ingests tegelijk ipv 1 per 1.

**Comment by Kris-LIBIS** [comment]
Dat doen we ondertussen al een tijd. De schaalbaarheid wordt echter beperkt door de mogelijkheden van de onderliggende tools, voornamelijk ImageMagick die random errors beginnen te genereren als veel processen tegelijk bezig zijn. Om deze bottleneck op te lossen moeten we de taken niet zozeer in parallel uitvoeren, maar eerder denken aan het inschakelen van meerdere servers. Misschien halen we betere concurrency als we de conversies in afzonderlijke Docker engines laten bollen. I.p.v. parallel uit te voeren zien we meer heil in het asynchroon uitvoeren van bepaalde processen. Een losstaand proces zou dan instaan voor de queueing van de opdrachten.
