### ISSUE TITLE
fasen parallel uitvoeren

### ISSUE THREAD

**Issue by samalloing** [Kris-LIBIS/LIBIS_Ingester#2]
Sommige fasen kunnen parallel uitgevoerd worden. vb het downloaden van metadata en het aanmaken van afgeleiden kunnen tegelijk gebeuren. ook andere fasen kunnen eventueel parallel uitgevoerd kunnen worden, maar metadata en het maken van afgeleiden zijn de belangrijkste.

**Comment by Kris-LIBIS** [comment]
Doen we niet. Het blijkt dat de ManifestationBuilder meestal toch het gros van de tijd in beslag neemt. De tijd die andere taken vergen is verwaarloosbaar. Er is veel meer tijdswinst te boeken door de ManifestationBuilder te laten werken met een dedicated server component die zelf meerdere conversies in parallel kan uitvoeren. Idem voor andere componenten die meer tijd vragen zoals de FormatIdentifier.
