### ISSUE TITLE
toevoegen van logical structmap

### ISSUE THREAD

**Issue by samalloing** [Kris-LIBIS/LIBIS_Ingester#3]
Op basis van een csv zou een logical structmap moeten toegevoegd kunnen worden

**Comment by samalloing** [comment]
Kolom 1 =filename zonder extensie, kolom 4 = nieuwe physical structmap, kolom 5 = nieuwe logical structmap
[metslabelTest.zip](https://github.com/Kris-LIBIS/LIBIS_Ingester/files/152800/metslabelTest.zip)

**Comment by Kris-LIBIS** [comment]
En nu kan ik helemaal niet meer volgen. In kolom 4 staat geen structuur, maar enkel een label. kolom 5 is leeg op enkele na ??

**Comment by samalloing** [comment]
Ja kolom 4 wordt dus de label (en dat is de physical structmap). Kolom 5 bevat idd maar enkel labels en wordt de logical structmap. De bedoeling is dat er zo snel naar een bepaald onderdeel kan gesprongen worden ipv te zoeken door de lange lijst. Vb zo zien ze waar de titel pagina begint, waar hoofdstuk 1, hoofdstuk 2,... begint.

**Comment by samalloing** [comment]
Versie 2, nu met de mets labels overal toegepast
[METSlabelv2.zip](https://github.com/Kris-LIBIS/LIBIS_Ingester/files/156421/METSlabelv2.zip)

**Comment by Kris-LIBIS** [comment]
Waarom wil je eigenlijk een logical structmap maken in Rosetta?

**Comment by samalloing** [comment]
Omdat dat een toegankelijker versie is voor de gebruikers (vb een boek opgedeeld in hoofdstukken). Voor de catalografen is het gemakkelijker en sneller om een boek te beschrijven.

**Comment by Kris-LIBIS** [comment]
Dat bedoel ik niet. Waarom wil je een LOGICAL structmap maken? In Rosetta zijn er uiteindelijk toch enkel representaties? Wisselen tussen structmaps is iets van Digitool en kan volgens mij niet in Rosetta – tenzij ik iets gemist heb. In Rosetta gebruik ik enkel physical structmaps. Vandaar mijn vraag.

In Rosetta is een taak ‘generate logical structmap’ die een nieuwe logical structmap maakt op basis van de ‘fileOriginalPath’ in de DNX. Het bestaat dus blijkbaar nog wel in Rosetta, maar het is mij niet duidelijk hoe dat er in de viewer uit gaat zien.

De mapping zou in het IngestModel moeten worden opgevangen want daar worden de representaties gedefinieerd. Die mapping files om de namen van bestanden te veranderen vind ik crap, want het kost evenveel moeite om de bestanden met de hand te hernoemen dan een Excel document te maken. Anderzijds moet het wel mogelijk zijn om de volgorde van de bestanden te bepalen, dus daarom kan een mapping file wel. De oplossing zou er dan op neer komen dat een manifestation in IngestModel een mapping file kan meekrijgen waarin voor elk bestand de volgorde, naam en submap kan worden bepaald.

Kunnen wij de structuur van de mapping file nog bepalen? Om die bestanden automatisch te laten verwerken lijkt het me bijvoorbeeld toch meer dan wenselijk om een header lijn toe te voegen. Dan kan de ingester overweg met andere volgorde van kolommen of het niet aanwezig zijn van een kolom. Dan wordt de actie tenminste toepasbaar op meerdere ingest types ipv enkel voor die ene ingest.

**Comment by samalloing** [comment]
Volgens het AIP document kan je een physical en een logical structmap aanmaken in de METS. Daarom moet het ook tijdens ingest gebeuren,want op dit moment is het niet mogelijk om via de API de mets-struct aan te passen . Met Mets-struct bedoel ik de metadata die in de managment omgeving de structmap info bevat. Je kan dat enkel manueel aanpassen.
http://knowledge.exlibrisgroup.com/@api/deki/files/39700/Rosetta_AIP_Data_Model.pdf (zie p 18 voor een voorbeeld hoe het in de viewer er uit zou zien)

Ja we kunnen het formaat van de mapping file nog laten aanpassen.

**Comment by samalloing** [comment]
[METSlabels.zip](https://github.com/Kris-LIBIS/LIBIS_Ingester/files/165518/METSlabels.zip)
Kolomnamen kunnen enkel als het Excel is. Is dat ook goed?

**Comment by samalloing** [comment]
Ik heb een mer file, excel, csv file en een xml file laten maken. De voorkeur gaat uit naar de mer file of excel file omdat we ook nog andere dingen met die files moeten doen en voor mensen is de mer of Excel file werkbaar, de XML file is niet erg bruikbaar.
Anders moet je een optie voorzien waar het formaat (; of ,) moet aangegeven worden, zoals je dat bij metadata formaat (tsv, csv) doet. Zo kunnen we met beide opties overweg. we kunnen er ook voor zorgen dat de bestandsnaam vb geen mer bevat, maar vb csv.
[CSV.zip](https://github.com/Kris-LIBIS/LIBIS_Ingester/files/166700/CSV.zip)

**Comment by Kris-LIBIS** [comment]
Done, maar op basis van de nieuwe afspraken rond concordantietabellen en mapping files.
