### ISSUE TITLE
linken van geingeste objecten aan Alma

### ISSUE THREAD

**Issue by samalloing** [Kris-LIBIS/LIBIS_Ingester#5]
Nu zoeken werkt, kan er ook een link gelegd worden tijdens ingesten van Rosetta naar Alma.De api van Alma laat het toe. Er moet geconfigureerd worden welk veld moet aangemaakt worden vb 856 40 $u en $y of e-portfolio of digital representation; Bij 856 krijgt $u de url van een IE of een (sub)-collection en $y een standaard tekst of de naam van de IE of collection

**Comment by Kris-LIBIS** [comment]
De informatie die nodig is om de URL te bouwen is niet beschikbaar op het moment van zoeken, maar enkel nadat het object goed is geingest.

**Comment by Kris-LIBIS** [comment]
De Alma API is hiervoor nog steeds niet beschikbaar. Alma links moeten met een job in Alma worden toegevoegd en het opstarten van de job moet manueel gebeuren waarbij een bestand moet worden toegevoegd. We maken nu een duidelijk export bestand na de ingest die ons toelaat om dit manuele proces zo vlot mogelijk te laten verlopen.
