### ISSUE TITLE
dc metadata wordt niet getoond in de collection viewer

### ISSUE THREAD

**Issue by samalloing** [Kris-LIBIS/LIBIS_Ingester#6]
De DC metadata verschijnt niet in de collection viewer. ik denk dat het is omdat je geen dc:record gebruikt, maar gewoon record. Volgens mij heeft Stephan dat probleem ook gehad en was dat de oplossing. Vb is collectionId=24261407 op test

**Comment by samalloing** [comment]
Ik heb verder naar het record gekeken. Er is maar één title

**Comment by Kris-LIBIS** [comment]
Je hebt ook geen metadata record aan de collectie gehangen tijdens de ingest. In de ingest databank zie ik een paar duizen collecties, maar geen enkele heeft er een metadata record aan hangen. Als je geen metadata meegeeft, maakt de CollectionCreator task er een voor je met een dc:title en eventueel dc:isPartOf veld. Het record dat wordt gemaakt heeft trouwens altijd dc:record als root element.

Nazicht van je configuratie geeft trouwens aan dat je als match_erm item.name aangeeft en de collectienaam is in het voorbeeld dat je aangeeft 2012-2013. In je metadatamapping zie ik daar niets van terug.
