### ISSUE TITLE
check op de accessrights mid

### ISSUE THREAD

**Issue by samalloing** [Kris-LIBIS/LIBIS_Ingester#7]
Er zou een check moeten zijn voor de ingest om te kijken of een bepaalde mid van de accessrights. Er is in Rosetta 5 vb getSharedMDByMid bij de IEWebServices. Deze functie zou vb gebruikt kunnen worden om dit te controleren.

**Comment by Kris-LIBIS** [comment]
Kan je je zin afmaken? ' om te kijken of ....'

Ik denk dat je wil zeggen om te kijken of AR bestaat. Wel dat gaan we niet via de AR API doen want die werkt niet naar behoren. Zoals gezegd worden de AR objecten (net zoals de retention policies) in de toekomst rechtstreeks uit de DB gelezen. Belangrijker is echter te weten of de AR in de material flow zitten en dat moet met de producer API. Maar ook daarmee zijn problemen zat.

**Comment by samalloing** [comment]
idd bestaat :-). Als ik getSharedMDByMid gebruik, dan geeft die toch de XML terug van de accessright.

Van de material flow zou ook idd interessant zijn, maar als dit al zou kunnen dan zou het al een hele hulp zijn om stomme fouten er uit te halen voor je de volledige ingest volledig doorloopt.

**Comment by Kris-LIBIS** [comment]
Gaan we niet doen. Het brengt te weinig op. In de praktijk zijn de problemen altijd dat ARs niet in de workflow worden toegevoegd en daar hebben we toch geen oplossing voor,
